# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [".node-version", "tsconfig.json", "package.json", "apps/kando/package.json", "apps/kando/package-lock.json", "patches/*", "apps/kando/src/main/example-menus/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Simon Schneegans <code@simonschneegans.de>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "apps/kando/locales/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Simon Schneegans <code@simonschneegans.de>"
SPDX-License-Identifier = "MIT"
